### ISSUE TITLE
iOS 回调问题

### ISSUE THREAD

**Issue by joeyczz** [fluttify-project/foundation_fluttify#12]
**插件版本**

**描述bug**
其他插件无法接收回调
`/**
 * Calls all plugins registered for `UIApplicationDelegate` callbacks in order of registration until
 * some plugin handles the request.
 *
 *  @return `YES` if any plugin handles the request.
 */
- (BOOL)application:(UIApplication*)application
            openURL:(NSURL*)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id>*)options;
`
不应该return YES
**复现步骤**

**期望行为**

**截图**
<img width="931" alt="WeChat4b8e290d954b9252d0c22af91dfde7b7" src="https://user-images.githubusercontent.com/15942257/77296012-d8fc8e80-6d21-11ea-82cb-baf25d012c9c.png">

**flutter doctor**

**Comment by yohom** [comment]
OK，我抽个版本改一下。
