### ISSUE TITLE
ios didFinishLaunchingWithOptions生命周期问题

### ISSUE THREAD

**Issue by JakeWoki** [fluttify-project/foundation_fluttify#13]
**插件版本**
0.6.1
amap_location_fluttify: ^0.11.0
amap_map_fluttify: ^0.21.0-dev.4
**描述bug**
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
}
```
我在另外一个插件关联了生命周期，上面的didFinishLaunchingWithOptions没有调用，如果我去掉amap_location_fluttify: ^0.11.0、amap_map_fluttify: ^0.21.0-dev.4，就可以正常调用，这个是冲突了，还是被覆盖被拦截了？不怎么懂ios
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by JakeWoki** [comment]
问了个ios的，说didFinishLaunchingWithOptions返回YES，我试试下到本地编译看看

**Comment by yohom** [comment]
现在最新版本都是返回`NO`了，应该不会被拦截
https://github.com/fluttify-project/foundation_fluttify/blob/afcaba4aec9fb3ea2a90268a2fc351420a8e2694/ios/Classes/FoundationFluttifyPlugin.m#L76

**Comment by JakeWoki** [comment]
@yohom 我刚刚把foundation_fluttify、core_location_fluttify、amap_core_fluttify、amap_location_fluttify、amap_map_fluttify下到本地，将依赖改成本地，还有把foundation_fluttify里的ios中的FoundationFluttifyPlugin.m里面的NO全部改成YES，这样后另一个插件的didFinishLaunchingWithOptions可以执行。
flutter的文档：``NO` if this vetoes application launch.`所以应该是YES

**Comment by JakeWoki** [comment]
顺便请教个问题：因为没有导航功能插件，我自己写了个导航功能的插件，高德的导航AMapNavi包含了地图，编译会导致冲突。android的在gradle里用resolutionStrategy可以排除，ios的要怎么处理？我现在手动查MAMapKit相关去掉可以编译，但是每次都这样显然不太好，有什么更好的方法吗？

**Comment by yohom** [comment]
> @yohom 我刚刚把foundation_fluttify、core_location_fluttify、amap_core_fluttify、amap_location_fluttify、amap_map_fluttify下到本地，将依赖改成本地，还有把foundation_fluttify里的ios中的FoundationFluttifyPlugin.m里面的NO全部改成YES，这样后另一个插件的didFinishLaunchingWithOptions可以执行。
> flutter的文档：`"NO" if this vetoes application launch.`所以应该是YES

这个是咋回事，issue #12 说法是返回YES拦截了回调导致其他插件无法接收到回调，难道不同的回调方法对这个返回值的处理还不一样？iOS我也没有很熟，可以问下你iOS同事确认一下这个事情吗

**Comment by yohom** [comment]
> 顺便请教个问题：因为没有导航功能插件，我自己写了个导航功能的插件，高德的导航AMapNavi包含了地图，编译会导致冲突。android的在gradle里用resolutionStrategy可以排除，ios的要怎么处理？我现在手动查MAMapKit相关去掉可以编译，但是每次都这样显然不太好，有什么更好的方法吗？

如果你是需要应用内驾车导航的话，我提供了一次性付费服务，参考 https://github.com/fluttify-project/foundation_fluttify/issues/13#issuecomment-619692497

**Comment by JakeWoki** [comment]
那个ios的是网页，他不熟悉这块。。。按文档didFinishLaunchingWithOptions、willFinishLaunchingWithOptions是`“NO” if this vetoes application launch`，其它是`“YES” if this handles the request`，应该didFinishLaunchingWithOptions、willFinishLaunchingWithOptions返回YES，其它返回NO

**Comment by yohom** [comment]
👌我抽个时间改一下
